### ISSUE TITLE
Bot ignores direction passed to mine() function

### ISSUE THREAD

**Issue by xelab04** [alantr7/codebots#1]
I think I found where the issue is. In [codebots/plugin/codeint/functions/MineFunction.java ](https://github.com/alantr7/codebots/blob/main/src/main/java/com/github/alantr7/codebots/plugin/codeint/functions/MineFunction.java) the bot appears to be using the vector (0, -1, 0) regardless of the direction argument passed. This causes the bot to mine the block directly underneath at all times.

![image](https://github.com/user-attachments/assets/1a56ee2a-c50a-4c63-8afe-1c0b499898e8)

I think it can be fixed by using the [Direction](https://github.com/alantr7/codebots/blob/main/src/main/java/com/github/alantr7/codebots/api/bot/Direction.java) if a cardinal direction is used (or up/down). And for mine forward/back you could get the bot's direction, pass it through the Direction enum, and add the vector to the location instead of (0, -1, 0)

Sorry, I would have loved to make a PR but I barely know Java and don't know how to run the code locally to test.

**Comment by alantr7** [comment]
Thank you for reporting! This is now implemented in 0.3.1.
